name: Run pre-commit

on:
  push:
    branches-ignore:
      - main
      - gh-pages

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version:  12.x

      - run: npm install

      - run: npm test
        env:
          CI: true

      - run: npm run build --if-present
