name: Run pre-commit

on:
  push:
    branches-ignore:
      - main
      - gh-pages

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Set PY env
        run: echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_ENV

      - name: Cache pre-commit env
        uses: actions/cache@v2.1.5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        uses: pre-commit/action@v1.0.1

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version:  12.x

      - run: npm install

      - run: npm test
        env:
          CI: true
